# Reference: https://github.com/i3/i3/blob/next/etc/config

config-version = 2

persistent-workspaces = []
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
    inner.horizontal = 10
    inner.vertical = 10
    outer.left = 10
    outer.bottom = 10
    outer.top = 10
    outer.right = 10

[mode.main.binding]
    alt-enter = '''exec-and-forget osascript -e '
    tell application "iTerm"
        create window with default profile
        activate
    end tell'
    '''

    alt-h = 'focus --boundaries-action wrap-around-the-workspace left'
    alt-j = 'focus --boundaries-action wrap-around-the-workspace down'
    alt-k = 'focus --boundaries-action wrap-around-the-workspace up'
    alt-l = 'focus --boundaries-action wrap-around-the-workspace right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    alt-g = 'split horizontal'
    alt-v = 'split vertical'

    alt-shift-q = 'close'
    alt-shift-f = 'macos-native-fullscreen'
    alt-shift-space = 'layout floating tiling' # toggle floating / tiling

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-0 = 'workspace 0'

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'
    alt-shift-0 = 'move-node-to-workspace 0'

    alt-shift-r = 'reload-config'
    alt-r = 'mode resize'

[mode.resize.binding]
    h = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width +50'
    enter = 'mode main'
    esc = 'mode main'

[workspace-to-monitor-force-assignment]
    0 = 'Built-in Retina Display'

[[on-window-detected]]
    if.app-id = 'com.googlecode.iterm2'
    run = 'move-node-to-workspace 1'
[[on-window-detected]]
    if.app-id = 'com.apple.dt.Xcode'
    run = 'move-node-to-workspace 2'
[[on-window-detected]]
    if.app-id = 'md.obsidian'
    run = 'move-node-to-workspace 2'
[[on-window-detected]]
    if.app-id = 'com.apple.Safari'
    run = 'move-node-to-workspace 3'
[[on-window-detected]]
    if.app-id = 'com.google.Chrome'
    run = 'move-node-to-workspace 3'
[[on-window-detected]]
    if.app-id = 'com.xnview.XnView'
    run = 'move-node-to-workspace 0'
[[on-window-detected]]
    if.app-id = 'com.apple.finder'
    run = 'layout floating'

[[on-window-detected]]
    if.app-id = 'com.apple.ActivityMonitor'
    run = 'layout floating'
[[on-window-detected]]
    if.app-id = 'com.macitbetter.betterzip'
    run = 'layout floating'
[[on-window-detected]]
    if.app-id = 'com.Replacicon.Replacicon'
    run = 'layout floating'
[[on-window-detected]]
    if.app-id = 'com.charliemonroe.Downie-4'
    run = 'layout floating'
[[on-window-detected]]
    if.app-id = 'org.m0k.transmission'
    run = 'layout floating'

[[on-window-detected]]
    if.app-id = 'com.valvesoftware.steam'
    run = ['layout floating', 'move-node-to-workspace 6']
[[on-window-detected]]
    if.app-id = 'com.valvesoftware.steam.helper'
    run = ['layout floating', 'move-node-to-workspace 6']
[[on-window-detected]]
    if.app-id = 'com.codeweavers.CrossOver'
    run = ['layout floating', 'move-node-to-workspace 6']
[[on-window-detected]]
    if.app-name-regex-substring = 'Mod Organizer'
    run = ['layout floating', 'move-node-to-workspace 6']
