#!/usr/bin/env bash
BATT_INFO=`acpi -b | grep 'Battery'`
BATTERY_C=`echo $BATT_INFO | awk '{printf("%s", $3);}'`
declare -i BATTERY_P=`echo $BATT_INFO | awk '{printf("%d", $4);}'`

icon_30=" "
icon_50=" "
icon_75=" "
icon_100=" "
icon_charge=" "
icon_full=" "
icon_output=""

# Output the battery icon by checking percentage
if [ $BATTERY_P -gt 5 ] && [ $BATTERY_P -le 30 ]; then
    icon_output+=$icon_30
elif [ $BATTERY_P -gt 30 ] && [ $BATTERY_P -le 50 ]; then
    icon_output+=$icon_50
elif [ $BATTERY_P -gt 50 ] && [ $BATTERY_P -le 75 ]; then
    icon_output+=$icon_75
elif [ $BATTERY_P -gt 75 ] && [ $BATTERY_P -le 100 ]; then
    icon_output+=$icon_100
else
    icon_output+="ERR_icon"
fi


# Output the charging icon by checking if battery is charging
if [ "$BATTERY_C" = "Discharging," ]; then
    icon_output+=""
elif [ "$BATTERY_C" = "Charging," ]; then
    icon_output+=$icon_charge
else
    icon_output+=$icon_charge
fi

echo "$icon_output"
