#!/usr/bin/env perl
use strict;
use warnings;
use utf8;

my $acpi;
my $status;
my $percent;
my $output;
my $bat_number = $ENV{BLOCK_INSTANCE} || 0;

# read the first line of the "acpi" command output
open (ACPI, "acpi -b | grep 'Battery $bat_number' |") or die;
$acpi = <ACPI>;
close(ACPI);

# fail on unexpected output
if($acpi !~ /: (\w+), (\d+)%/)
{
    die "$acpi\n";
}
$status = $1;
$percent = $2;

# if low on battery, quit the script.
if($percent < 5)
{
    exit(33);
}

# construct the output string.
$output = "$percent%";


if($status eq 'Full')
{
    $output = "100%";
}

# print text
print "$output\n";

exit(0);
