#!/usr/bin/perl

# File generated by menutray v0.50

# DO NOT edit this file!
# Any change in this file will be lost!
# Edit '/home/decimate/.config/menutray/schema.pl' instead!

use utf8;
use strict;
use Gtk2 ('-init');

my $menu = 'Gtk2::Menu'->new;
my $icon = 'Gtk2::StatusIcon'->new;

$icon->set_from_icon_name('start-here');
$icon->set_visible(1);
$icon->signal_connect('button-release-event', \&show_icon_menu);

load_menu();

sub show_icon_menu {
    $menu->popup(undef, undef, sub {return Gtk2::StatusIcon::position_menu($menu, 0, 0, $icon)}, [1, 1], 0, 0);
    return 1;
}

sub load_menu {
{
    my $item = 'Gtk2::ImageMenuItem'->new("Terminal");
    $item->set_image('Gtk2::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $item->signal_connect('activate', sub {system "urxvt &"});
    $menu->append($item);
}

{
    my $item = 'Gtk2::ImageMenuItem'->new("File\ Manager");
    $item->set_image('Gtk2::Image'->new_from_icon_name("system\-file\-manager",q{menu}));
    $item->signal_connect('activate', sub {system "xdg\-open\ \. &"});
    $menu->append($item);
}

{
    my $item = 'Gtk2::ImageMenuItem'->new("Web\ Browser");
    $item->set_image('Gtk2::Image'->new_from_icon_name("chromium",q{menu}));
    $item->signal_connect('activate', sub {system "chromium &"});
    $menu->append($item);
}

{
    my $item = 'Gtk2::ImageMenuItem'->new("Run\ command");
    $item->set_image('Gtk2::Image'->new_from_icon_name("system\-run",q{menu}));
    $item->signal_connect('activate', sub {system "rofi\ \-show\ run\ \-config\ \~\/\.Xdefaults &"});
    $menu->append($item);
}


    $menu->append('Gtk2::SeparatorMenuItem'->new);

    # # # # # # # # # # # # # # # # # # # # SETTINGS # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("Settings");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-system",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Fcitx\ Configuration");
    $app->signal_connect('activate', sub {system "fcitx\-configtool &"});
    $app->set_property('tooltip_text', "Change\ Fcitx\ Configuration");
    $app->set_image('Gtk2::Image'->new_from_icon_name("fcitx",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("KDE\ System\ Settings");
    $app->signal_connect('activate', sub {system "systemsettings5 &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-system",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("System\ Settings");
    $app->signal_connect('activate', sub {system "systemsettings5 &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-system",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("PulseAudio\ Volume\ Control");
    $app->signal_connect('activate', sub {system "pavucontrol &"});
    $app->set_property('tooltip_text', "Adjust\ the\ volume\ level");
    $app->set_image('Gtk2::Image'->new_from_icon_name("multimedia\-volume\-control",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # SYSTEM # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("System");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-system\-monitor",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("KSysGuard");
    $app->signal_connect('activate', sub {system "ksysguard &"});
    $app->set_property('tooltip_text', "Monitor\ running\ processes\ and\ system\ performance");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-system\-monitor",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Htop");
    $app->signal_connect('activate', sub {system "xterm\ \-e\ \'htop\' &"});
    $app->set_property('tooltip_text', "Show\ System\ Processes");
    $app->set_image('Gtk2::Image'->new_from_icon_name("htop",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("urxvt");
    $app->signal_connect('activate', sub {system "urxvt &"});
    $app->set_property('tooltip_text', "An\ unicode\ capable\ rxvt\ clone");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("ranger");
    $app->signal_connect('activate', sub {system "xterm\ \-e\ \'ranger\' &"});
    $app->set_property('tooltip_text', "Launches\ the\ ranger\ file\ manager");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Oracle\ VM\ VirtualBox");
    $app->signal_connect('activate', sub {system "VirtualBox &"});
    $app->set_property('tooltip_text', "Run\ several\ virtual\ systems\ on\ a\ single\ host\ computer");
    $app->set_image('Gtk2::Image'->new_from_icon_name("virtualbox",q{menu}));
    $menu1->append($app);
}

    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # ACCESSORIES # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("Accessories");
    $app->set_image('Gtk2::Image'->new_from_icon_name("system\-file\-manager",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Dolphin");
    $app->signal_connect('activate', sub {system "dolphin &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("system\-file\-manager",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Ark");
    $app->signal_connect('activate', sub {system "ark &"});
    $app->set_property('tooltip_text', "Work\ with\ file\ archives");
    $app->set_image('Gtk2::Image'->new_from_icon_name("ark",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # DEVELOPMENT # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("Development");
    $app->set_image('Gtk2::Image'->new_from_icon_name("CMakeSetup",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("CMake");
    $app->signal_connect('activate', sub {system "cmake\-gui &"});
    $app->set_property('tooltip_text', "Cross\-platform\ buildsystem");
    $app->set_image('Gtk2::Image'->new_from_icon_name("CMakeSetup",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("FLUID");
    $app->signal_connect('activate', sub {system "fluid &"});
    $app->set_property('tooltip_text', "FLTK\ GUI\ Designer");
    $app->set_image('Gtk2::Image'->new_from_icon_name("fluid",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt4\ Assistant");
    $app->signal_connect('activate', sub {system "assistant\-qt4 &"});
    $app->set_property('tooltip_text', "Shows\ Qt4\ documentation\ and\ examples");
    $app->set_image('Gtk2::Image'->new_from_icon_name("assistant\-qt4",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt4\ Designer");
    $app->signal_connect('activate', sub {system "designer\-qt4 &"});
    $app->set_property('tooltip_text', "Design\ GUIs\ for\ Qt4\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("designer\-qt4",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt4\ Linguist");
    $app->signal_connect('activate', sub {system "linguist\-qt4 &"});
    $app->set_property('tooltip_text', "Add\ translations\ to\ Qt4\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("linguist\-qt4",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt4\ QDbusViewer");
    $app->signal_connect('activate', sub {system "qdbusviewer\-qt4 &"});
    $app->set_property('tooltip_text', "Debug\ D\-Bus\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("qdbusviewer\-qt4",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt\ Assistant");
    $app->signal_connect('activate', sub {system "assistant &"});
    $app->set_property('tooltip_text', "Shows\ Qt\ documentation\ and\ examples");
    $app->set_image('Gtk2::Image'->new_from_icon_name("assistant",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt\ Designer");
    $app->signal_connect('activate', sub {system "designer &"});
    $app->set_property('tooltip_text', "Design\ GUIs\ for\ Qt\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("QtProject\-designer",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt\ Linguist");
    $app->signal_connect('activate', sub {system "linguist &"});
    $app->set_property('tooltip_text', "Add\ translations\ to\ Qt\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("linguist",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt\ QDbusViewer");
    $app->signal_connect('activate', sub {system "qdbusviewer &"});
    $app->set_property('tooltip_text', "Debug\ D\-Bus\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("qdbusviewer",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # NETWORK # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("Network");
    $app->set_image('Gtk2::Image'->new_from_icon_name("applications\-internet",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Thunderbird");
    $app->signal_connect('activate', sub {system "\/usr\/lib\/thunderbird\/thunderbird &"});
    $app->set_property('tooltip_text', "Send\ and\ receive\ mail\ with\ Thunderbird");
    $app->set_image('Gtk2::Image'->new_from_icon_name("thunderbird",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Chromium");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/chromium &"});
    $app->set_property('tooltip_text', "Browse\ the\ Web");
    $app->set_image('Gtk2::Image'->new_from_icon_name("chromium",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Tor\ Browser");
    $app->signal_connect('activate', sub {system "\/opt\/tor\-browser\-en\/INSTALL\/start\-tor\-browser\.desktop &"});
    $app->set_property('tooltip_text', "Tor\ Browser\ Bundle\:\ Anonymous\ browsing\ using\ firefox\ and\ tor");
    $app->set_image('Gtk2::Image'->new_from_pixbuf('Gtk2::Gdk::Pixbuf'->new_from_file_at_size("\/usr\/share\/pixmaps\/tor\-browser\-en\.png",16,16)));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Transmission");
    $app->signal_connect('activate', sub {system "transmission\-gtk &"});
    $app->set_property('tooltip_text', "Download\ and\ share\ files\ over\ BitTorrent");
    $app->set_image('Gtk2::Image'->new_from_icon_name("transmission",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # OFFICE # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("Office");
    $app->set_image('Gtk2::Image'->new_from_icon_name("applications\-office",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("WPS\ Writer");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/wps &"});
    $app->set_property('tooltip_text', "Use\ WPS\ Writer\ to\ edit\ articles\ and\ reports\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("wps\-office\-wpsmain",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("WPS\ Spreadsheets");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/et &"});
    $app->set_property('tooltip_text', "Use\ WPS\ Spreadsheets\ to\ analyze\ manage\ data\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("wps\-office\-etmain",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("WPS\ Presentation");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/wpp &"});
    $app->set_property('tooltip_text', "Use\ WPS\ Presentation\ to\ edit\ and\ play\ presentations\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("wps\-office\-wppmain",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # GRAPHICS # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("Graphics");
    $app->set_image('Gtk2::Image'->new_from_icon_name("applications\-graphics",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("FontForge");
    $app->signal_connect('activate', sub {system "fontforge &"});
    $app->set_property('tooltip_text', "An\ outline\ font\ editor");
    $app->set_image('Gtk2::Image'->new_from_icon_name("fontforge",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # MULTIMEDIA # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("Multimedia");
    $app->set_image('Gtk2::Image'->new_from_icon_name("applications\-multimedia",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Spotify");
    $app->signal_connect('activate', sub {system "spotify &"});
    $app->set_property('tooltip_text', "Spotify\ streaming\ music\ client");
    $app->set_image('Gtk2::Image'->new_from_icon_name("spotify\-client",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("VLC\ media\ player");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/vlc\ \-\-started\-from\-file &"});
    $app->set_property('tooltip_text', "Read\,\ capture\,\ broadcast\ your\ multimedia\ streams");
    $app->set_image('Gtk2::Image'->new_from_icon_name("vlc",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # GAMES # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("Games");
    $app->set_image('Gtk2::Image'->new_from_icon_name("applications\-games",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Steam\ \(Native\)");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/steam\-native &"});
    $app->set_property('tooltip_text', "Application\ for\ managing\ and\ playing\ games\ on\ Steam");
    $app->set_image('Gtk2::Image'->new_from_icon_name("steam",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Steam\ \(Runtime\)");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/steam\-runtime &"});
    $app->set_property('tooltip_text', "Application\ for\ managing\ and\ playing\ games\ on\ Steam");
    $app->set_image('Gtk2::Image'->new_from_icon_name("steam",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Steam\ \(Wine\)");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/steam-wine &"});
    $app->set_property('tooltip_text', "Application\ for\ managing\ and\ playing\ games\ on\ Steam\ \(Wine\ version\)");
    $app->set_image('Gtk2::Image'->new_from_icon_name("steam",q{menu}));
    $menu1->append($app);
}

    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # OTHER # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("Other");
    $app->set_image('Gtk2::Image'->new_from_icon_name("applications\-other",q{menu}));
    $app->set_submenu($menu1);
    $menu->append($app);
}

$menu->append('Gtk2::SeparatorMenuItem'->new);

{
    my $quit = 'Gtk2::ImageMenuItem'->new("Exit");
    $quit->set_property('tooltip_text', "Close\ this\ application\.");
    $quit->set_image('Gtk2::Image'->new_from_icon_name("exit",q{menu}));
    $quit->signal_connect('activate', sub { Gtk2->main_quit });
    $menu->append($quit);
}
    $menu->show_all;
    return 1;
}
'Gtk2'->main;
