# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# List of user stylesheet filenames to use.
# Type: List of File, or File
c.content.user_stylesheets = []

# Page to open if :open -t/-b/-w is used without URL. Use `about:blank`
# for a blank page.
# Type: FuzzyUrl
c.url.default_page = 'https://start.duckduckgo.com/'

# Page(s) to open at the start.
# Type: List of FuzzyUrl, or FuzzyUrl
c.url.start_pages = ['https://www.gentoo.org/', 'https://www.github.com/aesophor']

# Default zoom level.
# Type: Perc
c.zoom.default = '110%'

# Text color of the completion widget. May be a single color to use for
# all columns or a list of three colors, one for each column.
# Type: List of QtColor, or QtColor
c.colors.completion.fg = '#EEFFFF'

# Background color of the completion widget for odd rows.
# Type: QssColor
c.colors.completion.odd.bg = '#4A4A4A'

# Background color of the completion widget for even rows.
# Type: QssColor
c.colors.completion.even.bg = '#212121'

# Foreground color of completion widget category headers.
# Type: QtColor
c.colors.completion.category.fg = '#FFCB6B'

# Background color of the completion widget category headers.
# Type: QssColor
c.colors.completion.category.bg = '#212121'

# Top border color of the completion widget category headers.
# Type: QssColor
c.colors.completion.category.border.top = '#212121'

# Bottom border color of the completion widget category headers.
# Type: QssColor
c.colors.completion.category.border.bottom = '#212121'

# Foreground color of the selected completion item.
# Type: QtColor
c.colors.completion.item.selected.fg = '#303030'

# Background color of the selected completion item.
# Type: QssColor
c.colors.completion.item.selected.bg = '#FFCB6B'

# Top border color of the completion widget category headers.
# Type: QssColor
c.colors.completion.item.selected.border.top = '#FFCB6B'

# Bottom border color of the selected completion item.
# Type: QssColor
c.colors.completion.item.selected.border.bottom = '#FFCB6B'

# Foreground color of the matched text in the completion.
# Type: QssColor
c.colors.completion.match.fg = '#C3E88D'

# Color of the scrollbar handle in the completion view.
# Type: QssColor
c.colors.completion.scrollbar.fg = '#EEFFFF'

# Color of the scrollbar in the completion view.
# Type: QssColor
c.colors.completion.scrollbar.bg = '#212121'

# Background color for the download bar.
# Type: QssColor
c.colors.downloads.bar.bg = '#212121'

# Color gradient start for download text.
# Type: QtColor
c.colors.downloads.start.fg = '#212121'

# Color gradient start for download backgrounds.
# Type: QtColor
c.colors.downloads.start.bg = '#82AAFF'

# Color gradient end for download text.
# Type: QtColor
c.colors.downloads.stop.fg = '#212121'

# Color gradient stop for download backgrounds.
# Type: QtColor
c.colors.downloads.stop.bg = '#89DDFF'

# Foreground color for downloads with errors.
# Type: QtColor
c.colors.downloads.error.fg = '#F07178'

# Font color for hints.
# Type: QssColor
c.colors.hints.fg = '#212121'

# Background color for hints. Note that you can use a `rgba(...)` value
# for transparency.
# Type: QssColor
c.colors.hints.bg = '#FFCB6B'

# Font color for the matched part of hints.
# Type: QssColor
c.colors.hints.match.fg = '#EEFFFF'

# Text color for the keyhint widget.
# Type: QssColor
c.colors.keyhint.fg = '#EEFFFF'

# Highlight color for keys to complete the current keychain.
# Type: QssColor
c.colors.keyhint.suffix.fg = '#EEFFFF'

# Background color of the keyhint widget.
# Type: QssColor
c.colors.keyhint.bg = '#212121'

# Foreground color of an error message.
# Type: QssColor
c.colors.messages.error.fg = '#212121'

# Background color of an error message.
# Type: QssColor
c.colors.messages.error.bg = '#F07178'

# Border color of an error message.
# Type: QssColor
c.colors.messages.error.border = '#F07178'

# Foreground color of a warning message.
# Type: QssColor
c.colors.messages.warning.fg = '#212121'

# Background color of a warning message.
# Type: QssColor
c.colors.messages.warning.bg = '#C792EA'

# Border color of a warning message.
# Type: QssColor
c.colors.messages.warning.border = '#C792EA'

# Foreground color of an info message.
# Type: QssColor
c.colors.messages.info.fg = '#EEFFFF'

# Background color of an info message.
# Type: QssColor
c.colors.messages.info.bg = '#212121'

# Border color of an info message.
# Type: QssColor
c.colors.messages.info.border = '#212121'

# Foreground color for prompts.
# Type: QssColor
c.colors.prompts.fg = '#EEFFFF'

# Border used around UI elements in prompts.
# Type: String
c.colors.prompts.border = '#212121'

# Background color for prompts.
# Type: QssColor
c.colors.prompts.bg = '#212121'

# Background color for the selected item in filename prompts.
# Type: QssColor
c.colors.prompts.selected.bg = '#FFCB6B'

# Foreground color of the statusbar.
# Type: QssColor
c.colors.statusbar.normal.fg = '#C3E88D'

# Background color of the statusbar.
# Type: QssColor
c.colors.statusbar.normal.bg = '#212121'

# Foreground color of the statusbar in insert mode.
# Type: QssColor
c.colors.statusbar.insert.fg = '#212121'

# Background color of the statusbar in insert mode.
# Type: QssColor
c.colors.statusbar.insert.bg = '#82AAFF'

# Foreground color of the statusbar in passthrough mode.
# Type: QssColor
c.colors.statusbar.passthrough.fg = '#212121'

# Background color of the statusbar in passthrough mode.
# Type: QssColor
c.colors.statusbar.passthrough.bg = '#89DDFF'

# Foreground color of the statusbar in private browsing mode.
# Type: QssColor
c.colors.statusbar.private.fg = '#212121'

# Background color of the statusbar in private browsing mode.
# Type: QssColor
c.colors.statusbar.private.bg = '#4A4A4A'

# Foreground color of the statusbar in command mode.
# Type: QssColor
c.colors.statusbar.command.fg = '#EEFFFF'

# Background color of the statusbar in command mode.
# Type: QssColor
c.colors.statusbar.command.bg = '#212121'

# Foreground color of the statusbar in private browsing + command mode.
# Type: QssColor
c.colors.statusbar.command.private.fg = '#EEFFFF'

# Background color of the statusbar in private browsing + command mode.
# Type: QssColor
c.colors.statusbar.command.private.bg = '#212121'

# Foreground color of the statusbar in caret mode.
# Type: QssColor
c.colors.statusbar.caret.fg = '#212121'

# Background color of the statusbar in caret mode.
# Type: QssColor
c.colors.statusbar.caret.bg = '#C792EA'

# Foreground color of the statusbar in caret mode with a selection.
# Type: QssColor
c.colors.statusbar.caret.selection.fg = '#212121'

# Background color of the statusbar in caret mode with a selection.
# Type: QssColor
c.colors.statusbar.caret.selection.bg = '#82AAFF'

# Background color of the progress bar.
# Type: QssColor
c.colors.statusbar.progress.bg = '#82AAFF'

# Default foreground color of the URL in the statusbar.
# Type: QssColor
c.colors.statusbar.url.fg = '#EEFFFF'

# Foreground color of the URL in the statusbar on error.
# Type: QssColor
c.colors.statusbar.url.error.fg = '#F07178'

# Foreground color of the URL in the statusbar for hovered links.
# Type: QssColor
c.colors.statusbar.url.hover.fg = '#EEFFFF'

# Foreground color of the URL in the statusbar on successful load
# (http).
# Type: QssColor
c.colors.statusbar.url.success.http.fg = '#89DDFF'

# Foreground color of the URL in the statusbar on successful load
# (https).
# Type: QssColor
c.colors.statusbar.url.success.https.fg = '#C3E88D'

# Foreground color of the URL in the statusbar when there's a warning.
# Type: QssColor
c.colors.statusbar.url.warn.fg = '#C792EA'

# Background color of the tab bar.
# Type: QtColor
c.colors.tabs.bar.bg = '#212121'

# Color gradient start for the tab indicator.
# Type: QtColor
c.colors.tabs.indicator.start = '#82AAFF'

# Color gradient end for the tab indicator.
# Type: QtColor
c.colors.tabs.indicator.stop = '#89DDFF'

# Color for the tab indicator on errors.
# Type: QtColor
c.colors.tabs.indicator.error = '#F07178'

# Foreground color of unselected odd tabs.
# Type: QtColor
c.colors.tabs.odd.fg = '#EEFFFF'

# Background color of unselected odd tabs.
# Type: QtColor
c.colors.tabs.odd.bg = '#24292E'

# Foreground color of unselected even tabs.
# Type: QtColor
c.colors.tabs.even.fg = '#EEFFFF'

# Background color of unselected even tabs.
# Type: QtColor
c.colors.tabs.even.bg = '#24292E'

# Foreground color of selected odd tabs.
# Type: QtColor
c.colors.tabs.selected.odd.fg = '#EEFFFF'

# Background color of selected odd tabs.
# Type: QtColor
c.colors.tabs.selected.odd.bg = '#4A4A4A'

# Foreground color of selected even tabs.
# Type: QtColor
c.colors.tabs.selected.even.fg = '#EEFFFF'

# Background color of selected even tabs.
# Type: QtColor
c.colors.tabs.selected.even.bg = '#4A4A4A'

# Bindings for normal mode
config.bind('+', None)
config.bind(',m', "set content.user_stylesheets ''")
config.bind(',n', 'set content.user_stylesheets ~/.config/qutebrowser/css/solarized-dark-all-sites.css')
config.bind('-', None)
config.bind('<Ctrl+->', 'zoom-out')
config.bind('<Ctrl+0>', 'zoom')
config.bind('<Ctrl+=>', 'zoom-in')
config.bind('<Ctrl+h>', 'open -t ;; history')
config.bind('<Ctrl+t>', 'open -t')
config.bind('=', None)
config.bind('J', 'tab-prev')
config.bind('K', 'tab-next')
config.bind('d', None)
config.bind('t', 'set-cmd-text -s :open -t')
